# Pre-commit hooks configuration
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key

  # Python formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^backend/
        args: ['--line-length=100']

  # Python linting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^backend/

  # Python type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports, --python-version=3.11]
        files: ^backend/
        exclude: ^backend/(tests/|alembic/)

  # Frontend linting (ESLint)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.1
    hooks:
      - id: eslint
        files: ^frontend/.*\.(ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.57.1
          - '@typescript-eslint/eslint-plugin@7.18.0'
          - '@typescript-eslint/parser@7.18.0'
          - 'eslint-plugin-react-hooks@4.6.2'
          - 'eslint-plugin-react-refresh@0.4.12'
        args: ['--fix', '--max-warnings=0']

  # Frontend type checking (TypeScript)
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Type Check
        entry: bash -c 'cd frontend && pnpm type-check'
        language: system
        files: ^frontend/.*\.(ts|tsx)$
        pass_filenames: false
        always_run: false

