name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend-lint:
    name: Backend Linting (Black)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black mypy pytest pytest-cov
          pip install -r requirements.txt
      
      - name: Run Black (code formatting check)
        run: black --check --diff app/
      
      - name: Run Black (format if needed)
        run: black app/ || true
        continue-on-error: true

  backend-type-check:
    name: Backend Type Checking (mypy)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt
      
      - name: Run mypy
        run: mypy app/ --ignore-missing-imports || true
        continue-on-error: true

  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
      
      - name: Run tests
        run: pytest tests/ -v --cov=app --cov-report=xml || true
        continue-on-error: true
      
      - name: Upload coverage to Codecov (optional)
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
        continue-on-error: true

  frontend-lint:
    name: Frontend Linting (ESLint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run ESLint
        run: pnpm lint || true
        continue-on-error: true

  frontend-type-check:
    name: Frontend Type Checking (TypeScript)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run TypeScript type check
        run: pnpm exec tsc --noEmit || true
        continue-on-error: true

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build frontend
        run: pnpm build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'http://localhost:8000/api/v1' }}
          VITE_WS_URL: ${{ secrets.VITE_WS_URL || 'ws://localhost:8000/ws' }}

  docker-backend-build:
    name: Docker Backend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          target: production
          push: false
          tags: scims-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-frontend-build:
    name: Docker Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          target: production
          push: false
          tags: scims-frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL || 'http://localhost:8000/api/v1' }}
            VITE_WS_URL=${{ secrets.VITE_WS_URL || 'ws://localhost:8000/ws' }}

  docker-compose-build:
    name: Docker Compose Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build with docker-compose
        run: |
          docker compose -f docker-compose.yml build --no-cache
        continue-on-error: true

